name: Test

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install toolchain
              run: |
                sudo apt update
                sudo apt install -y build-essential

            - name: test
              run: make